// import 'package:hive/hive.dart';

// part 'user.g.dart'; // This file will be generated by Hive

// @HiveType(typeId: 0)
// class User {
//   @HiveField(0)
//   late String userImage;

//   @HiveField(1)
//   late String firstName;

//   @HiveField(2)
//   late String lastName;

//   @HiveField(3)
//   late String email;

//   @HiveField(4)
//   late String password;
// }

import 'package:hive/hive.dart';

part 'user.g.dart';

@HiveType(typeId: 0)
class User extends HiveObject {
  @HiveField(0)
  late String userImage;

  @HiveField(1)
  late String firstName;

  @HiveField(2)
  late String lastName;

  @HiveField(3)
  late String email;

  @HiveField(4)
  late String password;
}
